SERVER_PORT: 9090
CONTEXT_PATH: /api

############# DATABASE INFO ##################
DATABASE_URL: localhost
DATABASE_PASSWORD: root
DATABASE_USERNAME: postgres
DATABASE_NAME: database_test
DATABASE_PORT: 5432